using Pkg
Pkg.build("HDF5")
Pkg.add("JLD")
Pkg.add("SpecialFunctions")
Pkg.build("SpecialFunctions")
Pkg.add("FFTW")
Pkg.build("FFTW")
ENV["GRDIR"]="" ; Pkg.build("GR")
Pkg.add("PATHSolver")
Pkg.build("PATHSolver")
Pkg.add("SLEEFPirates")
Pkg.build("SLEEFPirates")
Pkg.add("IterTools")
Pkg.add("Tracker")
Pkg.add(Pkg.PackageSpec(url="https://github.com/SciML/Quadrature.jl", rev="master"))
Pkg.add(Pkg.PackageSpec(url="https://github.com/JuliaDiff/ForwardDiff.jl", rev="master"))
Pkg.add(Pkg.PackageSpec(url="https://github.com/JuliaDiff/FiniteDiff.jl", rev="master"))
Pkg.add(Pkg.PackageSpec(url="https://github.com/giordano/Cuba.jl", rev="master"))
Pkg.add("Zygote")
Pkg.add("DistributionsAD")
Pkg.add("HCubature")
Pkg.add("DataFrames")
Pkg.add("XLSX")
Pkg.add("Missings")
Pkg.add("Complementarity")
Pkg.add("JuMP")
Pkg.add("Ipopt")
Pkg.add("ApproxFun")
Pkg.add("PolyChaos")
Pkg.add("Cubature")

using LinearAlgebra, DataFrames, XLSX, Missings, JuMP, Ipopt, Random, Complementarity, LinearAlgebra, Test, Expectations, Distributions, NLsolve, DistributionsAD, SpecialFunctions, Quadrature
using Quadrature, ForwardDiff, FiniteDiff, Zygote, Cuba, DistributionsAD, Cubature, HCubature, Test, LinearAlgebra


Pkg.add(Pkg.PackageSpec(url="https://github.com/ABAtanasov/GalerkinSparseGrids.jl", rev="master"))